- name: Create autoexec.cfg
  file:
    path: "{{q3a_autoexec_cfg}}"
    state: touch

- name: Add default settings
  lineinfile:
    path: "{{q3a_autoexec_cfg}}"
    line: "{{item}}"
  with_items:
    - seta cg_fov "115"
    - seta cl_renderer "opengl2"
    - seta r_colorbits "32"
    - seta r_customheight "1200"
    - seta r_customwidth "1920"
    - seta r_depthbits "24"
    - seta r_fullscreen "1"
    - seta r_hdr "1"
    - seta r_lodbias "-2"
    - seta r_mode "-1"
    - seta r_picmip "0"
    - seta r_texturebits "32"
    - seta r_textureMode "GL_LINEAR_MIPMAP_LINEAR"
